[package]
name = "render_md_compile"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A small Rust binary for compiling Markdown files into a static site with a minimal templating language for variables, includes, conditionals, and styled blocks layered on top of pulldown-cmark"

[[bin]]
name = "compile_md"
path = "src/main.rs"

[features]
default = []
detailed-errors = ["render_md/detailed-errors"]

[dependencies]
render_md.workspace = true
miette.workspace = true
walkdir.workspace = true
clap = { version = "4", features = ["derive"] }
