[package]
name = "render_md"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A small Rust library for turning a directory of Markdown files into a static site (or a lazily-rendered, cached one), with a minimal templating language for variables, includes, conditionals, and styled blocks layered on top of pulldown-cmark"

[features]
default = []
detailed-errors = ["miette/fancy"]

[dependencies]
gray_matter.workspace = true
http.workspace = true
miette.workspace = true
pulldown-cmark.workspace = true
serde.workspace = true
tempfile.workspace = true
thiserror.workspace = true
thiserror-ext.workspace = true
walkdir.workspace = true
