server {
    listen 80;
    server_name localhost;
    root /var/www/public;

    # Serve images/css/js directly from Nginx (bypassing cgi-bin entirely)
    location /assets/ {
        try_files $uri =404;
    }

    # Render pages lazily, serve already rendered, non-stale pages and resources
    location / {
        include fastcgi_params;
        fastcgi_pass unix:/run/fcgiwrap.socket;

        fastcgi_param SCRIPT_FILENAME /var/www/cgi-bin/render_md;
        fastcgi_param TAILWIND_BIN /var/www/cgi-bin/tailwindcss;
        fastcgi_param APP_ROOT /var/www;
        fastcgi_param DOCUMENT_URI $uri;
        fastcgi_param DOCUMENT_TITLE Startpage;
        fastcgi_param DETAILED_ERRORS true; # requires binary built with --features detailed-errors
    }
}