name: Deploy example to GitHub Pages

on:
  push:
    branches: [main]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: DeterminateSystems/nix-installer-action@v17

      - uses: DeterminateSystems/magic-nix-cache-action@v9

      - name: Compile example site
        run: |
          nix develop --command bash -c '
              mkdir -p crates/render_md_cgi/examples/cgi_bin/public/{assets,error}
              cp crates/render_md_cgi/examples/cgi_bin/static/* \
              crates/render_md_cgi/examples/cgi_bin/public/assets/
              compile_md --base-dir crates/render_md_cgi/examples/cgi_bin
              # compile_md does not write failed pages to disk so we have to use render_mds output and skip the headers
              APP_ROOT=crates/render_md_cgi/examples/cgi_bin/ DOCUMENT_URI=/error render_md 2>&1 | tail -n +4 > /tmp/index.html
              mv /tmp/index.html crates/render_md_cgi/examples/cgi_bin/public/error
          '

      - uses: actions/upload-pages-artifact@v3
        with:
          path: crates/render_md_cgi/examples/cgi_bin/public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
